name: Coverage

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r app/test/requirements-test.txt

    - name: Run tests with coverage
      run: |
        cd app/test/
        coverage run -m pytest
        coverage report -m

    - name: Generate coverage badge
      run: |
        pip install coverage-badge
        cd app/test/
        coverage-badge -o coverage.svg

    - name: Commit and push badge
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add /home/runner/work/webhook-tester/webhook-tester/app/test/coverage.svg
        git commit -m "chore: update coverage badge"
        git push
